# Generated by Django 5.2.5 on 2025-09-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('coordinator', 'Coordinator'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
