# Generated by Django 5.2.5 on 2025-09-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('coordinator', 'Coordinator')], default='student', max_length=20),
        ),
    ]
