# Generated by Django 5.2.5 on 2025-09-10 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_classsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='student',
        ),
        migrations.AddField(
            model_name='classsession',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='class_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
