# Generated by Django 5.2.5 on 2025-09-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_classsession_student_classsession_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
